name: Build and Publish Docker Image

on:
  push:
    branches: [ "main", "master" ] # Se ejecuta cuando subes código a esta rama

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Permiso clave para subir la imagen a GitHub Packages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry (GHCR)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # Cambia "tu-usuario" por tu nombre de usuario de GitHub y "mi-restaurante" por el nombre de tu repo en minúsculas
          tags: ghcr.io/esteven2003/mi-restaurante-docker:latest